name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 20

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build backend
        working-directory: backend
        run: ./mvnw clean package -DskipTests

      - name: Run backend
        working-directory: backend
        run: java -jar target/*.jar &
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/testdb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
          SPRING_PROFILES_ACTIVE: test

      - name: Wait for backend
        run: npx wait-on http://localhost:8080/actuator/health
        env:
          WAIT_ON_TIMEOUT: 60000

      - name: Load test database
        run: |
          mysql --verbose --binary-mode=1 -h 127.0.0.1 -u root -proot testdb < backend/src/test/resources/full-database.sql

      - name: Install frontend dependencies
        working-directory: ./frontend/imdb-ratings-frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend/imdb-ratings-frontend
        run: npm run build

      - name: Start frontend
        working-directory: ./frontend/imdb-ratings-frontend
        run: npm run dev &

      - name: Wait for frontend
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        working-directory: ./frontend/imdb-ratings-frontend
        run: npx cypress run --config baseUrl=http://localhost:3000

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots

      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: frontend/cypress/videos
